export const quotes: { text: string, author: string }[] = [
  { text: 'The only thing that makes life possible is permanent, intolerable uncertainty; not knowing what comes next.', author: 'Ursula K. Le Guin' },
  { text: 'To learn which questions are unanswerable, and not to answer them: this skill is most needful in times of stress and darkness.', author: 'Ursula K. Le Guin' },
  { text: 'Writing is nothing more than a guided dream.', author: 'Jorge Luis Borges' },
  { text: 'A book is made of signs that speak of other signs, which in their turn speak of things.', author: 'Umberto Eco' },
  { text: 'That brain of mine is something more than merely mortal, as time will show.', author: 'Ada Lovelace' },
  { text: 'A writer is someone for whom writing is more difficult than it is for other people.', author: 'Thomas Mann' },
  { text: 'I have made this longer than usual because I have not had time to make it shorter.', author: 'Blaise Pascal' },
  { text: 'Work finally begins when the fear of doing nothing exceeds the fear of doing it badly.', author: 'Alain de Botton' },
  { text: 'Attention is the rarest and purest form of generosity.', author: 'Simone Weil' },
  { text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard' },
  { text: 'A poem is never finished, only abandoned.', author: 'Paul Val\u00e9ry' },
  { text: 'You do not need to leave your room. Remain sitting at your table and listen. The world will freely offer itself to you to be unmasked.', author: 'Franz Kafka' },
  { text: 'We are stuck with technology when what we really want is just stuff that works.', author: 'Douglas Adams' },
  { text: 'The only way to do great work is to be curious enough to explore and patient enough to persist.', author: 'Freeman Dyson' },
  { text: 'I learned very early the difference between knowing the name of something and knowing something.', author: 'Richard Feynman' },
  { text: 'The desire to write grows with writing.', author: 'Erasmus' },
  { text: 'Inspiration is for amateurs. The rest of us just show up and get to work.', author: 'Chuck Close' },
  { text: 'Start by doing what is necessary, then what is possible, and suddenly you are doing the impossible.', author: 'Francis of Assisi' },
  { text: 'You can always edit a bad page. You can\'t edit a blank page.', author: 'Jodi Picoult' },
  { text: 'The creation of something new is not accomplished by the intellect but by the play instinct.', author: 'Carl Jung' },
  { text: 'Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.', author: 'Antoine de Saint-Exup\u00e9ry' },
  { text: 'Everything that needs to be said has already been said. But since no one was listening, everything must be said again.', author: 'Andr\u00e9 Gide' },
  { text: 'The cure for boredom is curiosity. There is no cure for curiosity.', author: 'Ellen Parr' },
  { text: 'Have patience with everything unresolved in your heart and try to love the questions themselves.', author: 'Rainer Maria Rilke' },
  { text: 'The art of being wise is the art of knowing what to overlook.', author: 'William James' },
  { text: 'We don\'t receive wisdom; we must discover it for ourselves after a journey that no one can take for us or spare us.', author: 'Marcel Proust' },
  { text: 'The scariest moment is always just before you start.', author: 'Stephen King' },
  { text: 'If people sat outside and looked at the stars each night, I\'ll bet they\'d live a lot differently.', author: 'Bill Watterson' },
  { text: 'There is nothing so useless as doing efficiently that which should not be done at all.', author: 'Peter Drucker' },
  { text: 'The universe is full of magical things patiently waiting for our wits to grow sharper.', author: 'Eden Philpotts' },
  { text: 'Art is not what you see, but what you make others see.', author: 'Edgar Degas' },
  { text: 'You think your pain and your heartbreak are unprecedented in the history of the world, but then you read.', author: 'James Baldwin' },
  { text: 'People who are really serious about software should make their own hardware.', author: 'Alan Kay' },
  { text: 'Inside every cynical person, there is a disappointed idealist.', author: 'George Carlin' },
  { text: 'Inspiration exists, but it has to find you working.', author: 'Pablo Picasso' },
  { text: 'Work is love made visible.', author: 'Kahlil Gibran' },
  { text: 'I can\'t go on, I\'ll go on.', author: 'Samuel Beckett' },
  { text: 'To pay attention, this is our endless and proper work.', author: 'Mary Oliver' },
  { text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch' },
  { text: 'The imagination is not a state: it is the human existence itself.', author: 'William Blake' },
  { text: 'The best way out is always through.', author: 'Robert Frost' },
  { text: 'One must be drenched in words, literally soaked in them, to have the right ones form themselves into the proper pattern at the right moment.', author: 'Hart Crane' },
  { text: 'The task of a writer is not to solve the problem but to state the problem correctly.', author: 'Anton Chekhov' },
  { text: 'The most damaging phrase in the language is: "We\'ve always done it this way."', author: 'Grace Hopper' },
  { text: 'I do not fear computers. I fear the lack of them.', author: 'Isaac Asimov' },
  { text: 'Reading, after a certain age, diverts the mind too much from its creative pursuits. Any man who reads too much and uses his own brain too little falls into lazy habits of thinking.', author: 'Albert Einstein' },
  { text: 'It is perfectly okay to write garbage as long as you edit brilliantly.', author: 'C.J. Cherryh' },
  { text: 'The true mystery of the world is the visible, not the invisible.', author: 'Oscar Wilde' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Will Durant' },
  { text: 'No tears in the writer, no tears in the reader. No surprise in the writer, no surprise in the reader.', author: 'Robert Frost' },
  { text: 'Science is organized knowledge. Wisdom is organized life.', author: 'Will Durant' },
  { text: 'If an elderly but distinguished scientist says that something is possible, he is almost certainly right; but if he says that it is impossible, he is very probably wrong.', author: 'Arthur C. Clarke' }
]
